### ISSUE TITLE
Pieces place in a random spot a small percentage of the time

### ISSUE THREAD

**Issue by Kai-Richardson** [RJMNillo/CS301ASSN5GoTest#1]
Bug description:
Cannot choose where to place pieces some of the time, places it in a random spot upon pressing confirm.

To reproduce:
Sometimes when placing, your move either defaults to placing at top left corner or places in a random spot.

Addendum: This is only reproducible sometimes, trying to narrow down a test case.

**Comment by VandanBh** [comment]
Thank you for pointing it out!

**Comment by Kai-Richardson** [comment]
Fixed.
