### ISSUE TITLE
Smart AI does not perform any actions except pass

### ISSUE THREAD

**Issue by Kai-Richardson** [RJMNillo/CS301ASSN5GoTest#10]
Description:
The Smart AI does not perform any actions whatsoever.

To Reproduce:
Load up a game with the Smart AI. Try placing pieces, and the AI will simply pass and let you place pieces forever. You cannot win either, to end this loop.

**Comment by MwKau** [comment]
The Smart AI is being developed, but it is currently fixed! Thanks

**Comment by zmader** [comment]
This bug was fixed.
