### ISSUE TITLE
5.	Major Issue: Does not allow human player to place pieces after certain amount of passing.

### ISSUE THREAD

**Issue by saligumb22** [RJMNillo/CS301ASSN5GoTest#11]
To reproduce this bug, the human player has to keep passing until the computer player does not make any more turns. Once this has happened, if the human player tries to place a piece down and confirm a move, it does not allow it.

**Comment by MwKau** [comment]
This is most likely due to the game ending. But I will try to reproduce this. Thanks!

**Comment by braedenlane** [comment]
This is how the game is intended to be played. Once a pass is performed, it is the other players turn. Once two passes are done consecutively, the game is over, so no more pieces would be able to be played by either player. It was not that the AI did not make a move, it was that they passed, so the game would be over.

**Comment by saligumb22** [comment]
Issue has been fixed, the game allows you to place pieces until end of game.
