### ISSUE TITLE
Dumb AI Player does not catch for IllegalMoveInfo

### ISSUE THREAD

**Issue by alexjmak** [RJMNillo/CS301ASSN5GoTest#3]
For the dumb AI the game crashes if it played an illegal move because it crashes because on line 22, it tries to cast the GameInfo object to a GoState object when it really is an IllegalMoveInfo object.

**Comment by MwKau** [comment]
Nice catch! Fixed.

**Comment by alexjmak** [comment]
Yes, this bug is fixed.
