### ISSUE TITLE
[RUNTIME] State.getPeice has ArrayIndexOutOfBoundsException on piece placed

### ISSUE THREAD

**Issue by justin-23** [RJMNillo/CS301ASSN5GoTest#5]
When a piece placed in the left-most column, game immediately crashes. Reproduce by putting a piece in left-most column. (Can happen immediately after launching app) (GUI / Major).

**Comment by braedenlane** [comment]
We adjusted the code that produced this

**Comment by justin-23** [comment]
Bug fixed. Pieces placed in left-most column now have normal behavior.
