### ISSUE TITLE
Dumb AI stops placing pieces on turn 50 due to pass variable

### ISSUE THREAD

**Issue by Kai-Richardson** [RJMNillo/CS301ASSN5GoTest#6]
Description:
After getting fairly into a game, the Dumb AI just decided to stop placing pieces. This is caused by the pass value getting too large (>1).

To Reproduce:
Start a game, and play past 50 moves.
The pass value will get over 1, and the AI will stop placing.

To Fix:
Decrement your pass variable here:
https://github.com/RJMNillo/CS301ASSN5GoTest/blob/a452190150ac5d56edddbb146cb750fce313ef5b/app/src/main/java/com/example/cs301assn5go/Go/GoDumbAI.java#L26-L27

**Comment by MwKau** [comment]
Not a bug, but I will change this. Thanks!

**Comment by zmader** [comment]
This is now working correctly.
