### ISSUE TITLE
Stone placed in upper-left hand corner if the user plays outside of the board

### ISSUE THREAD

**Issue by TreyDettmer** [RJMNillo/CS301ASSN5GoTest#7]
(minor/ GUI) If there is no stone in the upper-left hand corner and the user chooses a location that is outside of the board area, then a stone is placed in the upper-left hand corner.

To reproduce this issue, tap outside of the board then press confirm. If there was no stone previously in the upper-left hand corner of the board, there should be one now.

**Comment by VandanBh** [comment]
Fixed, to where you see it flash red instead indicating that you are making an illegal move. Thank you!

**Comment by TreyDettmer** [comment]
Yep it is definitely fixed.
