### ISSUE TITLE
Captures aren't displayed

### ISSUE THREAD

**Issue by vickersk** [RJMNillo/CS301ASSN5GoTest#8]
Description:
When an opposing team's stone is captured, it is removed but the capture is not displayed in the TextView as a result.

To reproduce:
If you place multiple stones around an opposing player's stone, the stone will eventually be removed, but there is no indication that the piece has been captured.

Severity: Minor. The game is still playable and you can understand that the piece has been captured. 

Component: GUI

**Comment by RJMNillo** [comment]
setText implemented; captures can now be displayed.

**Comment by RJMNillo** [comment]
Oh shoots just realized I can say close issue and do that comment

**Comment by vickersk** [comment]
When an opposing player's piece is captured it is displayed. It appears the issue has been fixed.
